/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.bentley.mathml.svg;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        MathMLToSVG classUnderTest = new MathMLToSVG();
        //assertTrue(classUnderTest.getFunctionQName(), "should return true?");
    }
}
